packages:
  - src/*

catalog:
  "@ai-sdk/google": ^2.0.0
  "@ai-sdk/openai": ^2.0.89
  "@mastra/core": ^1.0.4
  "@mastra/express": ^1.0.1
  "@mastra/libsql": ^1.0.0
  "@mastra/loggers": ^1.0.4
  "@mastra/mcp": ^1.0.4
  "@mastra/memory": ^1.0.0
  "@mastra/observability": ^1.0.4
  "@mastra/otel-exporter": ^1.0.4
  "@mastra/pg": ^1.0.0
  "@mastra/rag": ^1.0.4
  "@modelcontextprotocol/sdk": ^1.24.3
  "@opentelemetry/api": ^1.9.0
  "@opentelemetry/auto-instrumentations-node": ^0.67.2
  "@opentelemetry/core": ^2.2.0
  "@opentelemetry/exporter-logs-otlp-http": ^0.208.0
  "@opentelemetry/exporter-metrics-otlp-http": ^0.208.0
  "@opentelemetry/exporter-trace-otlp-http": ^0.208.0
  "@opentelemetry/instrumentation": ^0.208.0
  "@opentelemetry/resources": ^2.2.0
  "@opentelemetry/sdk-logs": ^0.208.0
  "@opentelemetry/sdk-metrics": ^2.2.0
  "@opentelemetry/sdk-node": ^0.208.0
  "@opentelemetry/sdk-trace-base": ^2.2.0
  "@opentelemetry/sdk-trace-node": ^2.2.0
  "@opentelemetry/semantic-conventions": ^1.29.0
  "@types/better-sqlite3": ^7.6.12
  "@types/inquirer": ^9.0.7
  "@types/js-yaml": ^4.0.9
  "@types/micromatch": ^4.0.9
  "@types/node": ^24.10.1
  "@types/pg": ^8.11.10
  "@eslint/js": ^9.17.0
  "typescript-eslint": ^8.19.1
  "@vitest/coverage-v8": ^4.0.16
  ai: ^5.0.123
  axios: ^1.13.2
  better-sqlite3: ^11.10.0
  chalk: ^5.3.0
  chokidar: ^3.5.3
  commander: ^12.0.0
  cron-parser: ^4.9.0
  date-fns: ^3.0.0
  date-fns-tz: ^3.0.0
  dotenv: ^17.2.3
  dotenv-expand: ^12.0.3
  eslint: ^9.39.1
  express: ^5.1.0
  fast-glob: ^3.3.2
  inquirer: ^9.2.12
  js-yaml: ^4.1.1
  micromatch: ^4.0.8
  nats: ^2.29.3
  openai: ^4.104.0
  pg: ^8.16.3
  pino: ^9.6.0
  pino-pretty: ^13.1.3
  prettier: ^3.7.4
  tsup: ^8.5.1
  tsx: ^4.21.0
  turbo: ^2.6.3
  typescript: ^5.9.3
  undici: ^6.0.0
  uuid: ^13.0.0
  vitest: ^4.0.16
  yaml: ^2.8.2
  zod: ^3.23.8

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - protobufjs
